[package]
name = "cubegen"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.28.1"
color-eyre = "0.6.3"
futures = "0.3.31"
crossterm = {version = "0.28.1", features = ["event-stream"]}
tokio = {version = "1.40.0", features = ["full"]}

[profile.dev.package.backtrace]
opt-level = 3
